import Vue from 'vue';
import Vuex from 'vuex';
import VueRouter from 'vue-router';
import Vuetify from 'vuetify';
import axios from 'axios';
import VueDeepSet from 'vue-deepset';
import VueI18n from 'vue-i18n';
import * as VeeValidate from 'vee-validate';
import { Splitpanes, Pane } from 'splitpanes';
import Sortable from 'sortablejs';
import draggable from 'vuedraggable';
import VueJsonPretty from 'vue-json-pretty';
import _ from 'lodash';
import moment from 'moment';
import Ajv from 'ajv';
import deepdash from 'deepdash-es';
import L from 'leaflet';
import Chart from 'chart.js';
import jQuery from 'jquery';

// Make globals available (many components reference these as globals)
window.Vue = Vue;
window.Vuex = Vuex;
window.VueRouter = VueRouter;
window.axios = axios;
window._ = _;
window.moment = moment;
window.VueDeepSet = VueDeepSet;
window.VeeValidate = VeeValidate;
window.Vuetify = Vuetify;
window.VueI18n = VueI18n;
window.Sortable = Sortable;
window.draggable = draggable;
window.VueJsonPretty = VueJsonPretty;
window.Ajv = Ajv;
window.deepdash = deepdash;
window.L = L;
window.Chart = Chart;
window.jQuery = jQuery;
window.$ = jQuery;
window.splitpanes = { Splitpanes, Pane };

// Install plugins
Vue.use(Vuex);
Vue.use(VueDeepSet);
Vue.use(Vuetify);
Vue.use(VueI18n);

// Import and install EventBus + global methods
import { EventBus, installGlobalMethods } from '@views/vue/vue-global-eventbus.js';
window.EventBus = EventBus;
installGlobalMethods();

// window.bus (used in index_vuetify_main_app.php)
window.bus = new Vue();

// Import the global mixin
import globalMixin from '@/mixins/global-mixin.js';
Vue.mixin(globalMixin);

// Import shared components
import AlertDialog from '@views/vue/vue-alert-dialog-component.js';
import ConfirmDialog from '@views/vue/vue-confirm-dialog-component.js';
import GlobalSiteHeader from '@views/editor_common/global-site-header-component.js';

// Import metadata_editor components
import ProjectExportJson from '@views/metadata_editor/vue-project-export-json-component.js';
import TemplateValidation from '@views/metadata_editor/vue-template-validation-component.js';
import TemplateApplyDefaults from '@views/metadata_editor/vue-template-apply-defaults-component.js';
import ToastComponent from '@views/metadata_editor/vue-toast-component.js';
import LoginComponent from '@views/metadata_editor/vue-login-component.js';
import FieldDate from '@views/metadata_editor/fields/vue-field-date.js';
import FieldBoundingBox from '@views/metadata_editor/fields/vue-field-bounding-box.js';
import FieldText from '@views/metadata_editor/fields/vue-field-text.js';
import SpreadMetadata from '@views/metadata_editor/vue-spreadmetadata-component.js';
import FormMain from '@views/metadata_editor/vue-form-main-component.js';
import FormComponent from '@views/metadata_editor/vue-form-component.js';
import FormPreview from '@views/metadata_editor/vue-form-preview-component.js';
import NestedSectionPreview from '@views/metadata_editor/vue-nested-section-preview-component.js';
import FilesComponent from '@views/metadata_editor/vue-files-component.js';
import ExternalResourcesComponent from '@views/metadata_editor/vue-external-resources-component.js';
import ExternalResourcesEdit from '@views/metadata_editor/vue-external-resources-edit-component.js';
import ResumableFileUpload from '@views/metadata_editor/vue-resumable-file-upload-component.js';
import ExternalResourcesCreate from '@views/metadata_editor/vue-external-resources-create-component.js';
import DatafilesComponent from '@views/metadata_editor/vue-datafiles-component.js';
import DatafileEdit from '@views/metadata_editor/vue-datafile-edit-component.js';
import DatafileComponent from '@views/metadata_editor/vue-datafile-component.js';
import DatafileImport from '@views/metadata_editor/vue-datafile-import-component.js';
import DatafileDataExplorer from '@views/metadata_editor/vue-datafile-data-explorer-component.js';
import DialogDatafileExport from '@views/metadata_editor/vue-dialog-datafile-export-component.js';
import DialogBatchExport from '@views/metadata_editor/vue-dialog-batch-export-component.js';
import DialogBatchSumStatsOptions from '@views/metadata_editor/vue-dialog-batch-sum-stats-options-component.js';
import VariableEditDocumentation from '@views/metadata_editor/vue-variable-edit-documentation-component.js';
import VariablesComponent from '@views/metadata_editor/vue-variables-component.js';
import VariablesValidation from '@views/metadata_editor/vue-variables-validation-component.js';
import VariableEdit from '@views/metadata_editor/vue-variable-edit-component.js';
import VariableWeights from '@views/metadata_editor/vue-variable-weights-component.js';
import VariableCategories from '@views/metadata_editor/vue-variable-categories-component.js';
import VariableInfoEdit from '@views/metadata_editor/vue-variable-info-edit-component.js';
import FormTree from '@views/metadata_editor/vue-form-tree.js';
import GridComponent from '@views/metadata_editor/vue-grid-component.js';
import GridPreview from '@views/metadata_editor/vue-grid-preview-component.js';
import NestedSection from '@views/metadata_editor/vue-nested-section-component.js';
import FormInput from '@views/metadata_editor/vue-form-input-component.js';
import NestedArray from '@views/metadata_editor/vue-nested-array-component.js';
import SimpleArray from '@views/metadata_editor/vue-simple-array-component.js';
import TableComponent from '@views/metadata_editor/vue-table-component.js';
import GeospatialIdentification from '@views/metadata_editor/vue-geospatial-identification-component.js';
import ImportOptions from '@views/metadata_editor/vue-import-options-component.js';
import PublishOptions from '@views/metadata_editor/vue-publish-options-component.js';
import SdmxCsvExport from '@views/metadata_editor/vue-sdmx-csv-export-component.js';
import ProjectPackage from '@views/metadata_editor/vue-project-package-component.js';
import ExternalResourcesImport from '@views/metadata_editor/vue-external-resources-import-component.js';
import ConfigureCatalog from '@views/metadata_editor/vue-configure-catalog-component.js';
import SummaryComponent from '@views/metadata_editor/vue-summary-component.js';
import SummaryFiles from '@views/metadata_editor/vue-summary-files-component.js';
import SummarySharing from '@views/metadata_editor/vue-summary-sharing-component.js';
import ThumbnailComponent from '@views/metadata_editor/vue-thumbnail-component.js';
import TableGrid from '@views/metadata_editor/vue-table-grid-component.js';
import NestedSectionSubsection from '@views/metadata_editor/vue-nested-section-subsection-component.js';
import RepeatedField from '@views/metadata_editor/vue-repeated-field-component.js';
import FormSection from '@views/metadata_editor/vue-form-section-component.js';
import GeneratePdf from '@views/metadata_editor/vue-generate-pdf-component.js';
import VariableGroups from '@views/metadata_editor/vue-variable-groups-component.js';
import DialogVariableSelection from '@views/metadata_editor/vue-dialog-variable-selection-component.js';
import DialogWeightVariableSelection from '@views/metadata_editor/vue-dialog-weight-variable-selection-component.js';
import DialogComponent from '@views/metadata_editor/vue-dialog-component.js';
import DialogDatafileReplace from '@views/metadata_editor/vue-dialog-datafile-replace-component.js';
import DialogEnumSelection from '@views/metadata_editor/vue-dialog-enum-selection-component.js';
import GeospatialFeature from '@views/metadata_editor/vue-geospatial-feature-component.js';
import PagePreview from '@views/metadata_editor/vue-page-preview-component.js';
import GeospatialGallery from '@views/metadata_editor/vue-geospatial-gallery-component.js';
import ProjectShare from '@views/project/vue-project-share-component.js';
import CollectionShare from '@views/project/vue-collection-share-component.js';
import SummaryCollections from '@views/metadata_editor/vue-summary-collections-component.js';
import ProjectTags from '@views/metadata_editor/vue-project-tags-component.js';
import TextareaLatex from '@views/metadata_editor/vue-textarea-latex-component.js';
import ProjectHistory from '@views/metadata_editor/vue-project-history-component.js';
import AdminMetadataHistory from '@views/metadata_editor/vue-admin-metadata-history-component.js';
import MetadataTypeEdit from '@views/metadata_editor/vue-metadata-type-edit-component.js';
import MetadataTypes from '@views/metadata_editor/vue-metadata-types-component.js';
import SchemaArrayField from '@views/metadata_editor/vue-schema-array-field-component.js';
import SchemaObjectField from '@views/metadata_editor/vue-schema-object-field-component.js';
import AdminMetadataEdit from '@views/metadata_editor/vue-admin-metadata-edit-component.js';
import DialogAdminMetadata from '@views/metadata_editor/vue-dialog-admin-metadata-component.js';
import SummaryTemplates from '@views/metadata_editor/vue-summary-templates-component.js';
import JsonEdit from '@views/metadata_editor/vue-json-edit-component.js';
import ValidationReport from '@views/metadata_editor/vue-validation-report-component.js';
import GeospatialFeatures from '@views/metadata_editor/vue-geospatial-features-component.js';
import GeospatialFeatureEdit from '@views/metadata_editor/vue-geospatial-feature-edit-component.js';
import GeospatialFeatureImport from '@views/metadata_editor/vue-geospatial-feature-import-component.js';
import GeospatialFeatureCharacteristics from '@views/metadata_editor/vue-geospatial-feature-characteristics-component.js';
import GeospatialFeatureData from '@views/metadata_editor/vue-geospatial-feature-data-component.js';
import GeospatialFeatureDescription from '@views/metadata_editor/vue-geospatial-feature-description-component.js';
import IndicatorDsd from '@views/metadata_editor/vue-indicator-dsd-component.js';
import IndicatorDsdEdit from '@views/metadata_editor/vue-indicator-dsd-edit-component.js';
import IndicatorDsdImport from '@views/metadata_editor/vue-indicator-dsd-import-component.js';
import IndicatorDsdChart from '@views/metadata_editor/vue-indicator-dsd-chart-component.js';
import VariablesDiff from '@views/metadata_editor/vue-variables-diff-component.js';
import HelloComponent from '@views/metadata_editor/vue-hello-component.js';

// Register all components globally
Vue.component('alert-dialog', AlertDialog);
Vue.component('confirm-dialog', ConfirmDialog);
Vue.component('vue-global-site-header', GlobalSiteHeader);
Vue.component('project-export-json-component', ProjectExportJson);
Vue.component('template-validation-component', TemplateValidation);
Vue.component('template-apply-defaults-component', TemplateApplyDefaults);
Vue.component('v-toast', ToastComponent);
Vue.component('v-login', LoginComponent);
Vue.component('editor-date-field', FieldDate);
Vue.component('editor-bounding-box-field', FieldBoundingBox);
Vue.component('editor-text-field', FieldText);
Vue.component('spread-metadata', SpreadMetadata);
Vue.component('form-main', FormMain);
Vue.component('v-form', FormComponent);
Vue.component('v-form-preview', FormPreview);
Vue.component('nested-section-preview', NestedSectionPreview);
Vue.component('file-manager', FilesComponent);
Vue.component('external-resources', ExternalResourcesComponent);
Vue.component('external-resources-edit', ExternalResourcesEdit);
Vue.component('resumable-file-upload', ResumableFileUpload);
Vue.component('external-resources-create', ExternalResourcesCreate);
Vue.component('datafiles', DatafilesComponent);
Vue.component('datafile-edit', DatafileEdit);
Vue.component('datafile', DatafileComponent);
Vue.component('datafile-import', DatafileImport);
Vue.component('datafile-data-explorer', DatafileDataExplorer);
Vue.component('dialog-datafile-export', DialogDatafileExport);
Vue.component('dialog-batch-export', DialogBatchExport);
Vue.component('dialog-batch-sum-stats-options', DialogBatchSumStatsOptions);
Vue.component('variable-edit-documentation', VariableEditDocumentation);
Vue.component('variables', VariablesComponent);
Vue.component('variables-validation', VariablesValidation);
Vue.component('variable-edit', VariableEdit);
Vue.component('variable-weights-component', VariableWeights);
Vue.component('variable-categories', VariableCategories);
Vue.component('variable-info', VariableInfoEdit);
Vue.component('form-tree', FormTree);
Vue.component('grid-component', GridComponent);
Vue.component('grid-preview-component', GridPreview);
Vue.component('nested-section', NestedSection);
Vue.component('form-input', FormInput);
Vue.component('nested-array', NestedArray);
Vue.component('simple-array-component', SimpleArray);
Vue.component('table-component', TableComponent);
Vue.component('identification-section', GeospatialIdentification);
Vue.component('import-options', ImportOptions);
Vue.component('publish-options', PublishOptions);
Vue.component('sdmx-csv-export-options', SdmxCsvExport);
Vue.component('project-package', ProjectPackage);
Vue.component('external-resources-import', ExternalResourcesImport);
Vue.component('configure-catalog', ConfigureCatalog);
Vue.component('summary-component', SummaryComponent);
Vue.component('summary-files', SummaryFiles);
Vue.component('vue-summary-sharing-stats', SummarySharing);
Vue.component('project-thumbnail', ThumbnailComponent);
Vue.component('table-grid-component', TableGrid);
Vue.component('nested-section-subsection', NestedSectionSubsection);
Vue.component('repeated-field', RepeatedField);
Vue.component('form-section', FormSection);
Vue.component('generate-pdf', GeneratePdf);
Vue.component('variable-groups', VariableGroups);
Vue.component('dialog-variable-selection', DialogVariableSelection);
Vue.component('dialog-weight-variable-selection', DialogWeightVariableSelection);
Vue.component('vue-dialog-component', DialogComponent);
Vue.component('dialog-datafile-replace', DialogDatafileReplace);
Vue.component('vue-dialog-enum-selection-component', DialogEnumSelection);
Vue.component('geospatial-feature', GeospatialFeature);
Vue.component('page-preview', PagePreview);
Vue.component('geospatial-gallery', GeospatialGallery);
Vue.component('vue-project-share', ProjectShare);
Vue.component('vue-collection-share', CollectionShare);
Vue.component('vue-summary-collections', SummaryCollections);
Vue.component('vue-project-tags', ProjectTags);
Vue.component('v-textarea-latex', TextareaLatex);
Vue.component('project-history', ProjectHistory);
Vue.component('admin-metadata-history', AdminMetadataHistory);
Vue.component('metadata-types-edit', MetadataTypeEdit);
Vue.component('metadata-types', MetadataTypes);
Vue.component('schema-array-field', SchemaArrayField);
Vue.component('schema-object-field', SchemaObjectField);
Vue.component('admin-metadata-edit', AdminMetadataEdit);
Vue.component('vue-dialog-admin-metadata-component', DialogAdminMetadata);
Vue.component('summary-templates-component', SummaryTemplates);
Vue.component('json-edit', JsonEdit);
Vue.component('validation-report', ValidationReport);
Vue.component('geospatial-features', GeospatialFeatures);
Vue.component('geospatial-feature-edit', GeospatialFeatureEdit);
Vue.component('geospatial-feature-import', GeospatialFeatureImport);
Vue.component('geospatial-feature-characteristics', GeospatialFeatureCharacteristics);
Vue.component('geospatial-feature-data', GeospatialFeatureData);
Vue.component('geospatial-feature-description', GeospatialFeatureDescription);
Vue.component('indicator-dsd', IndicatorDsd);
Vue.component('indicator-dsd-edit', IndicatorDsdEdit);
Vue.component('indicator-dsd-import', IndicatorDsdImport);
Vue.component('indicator-dsd-chart', IndicatorDsdChart);
Vue.component('variables-diff', VariablesDiff);
Vue.component('hello', HelloComponent);

// Register third-party components
Vue.component('ValidationProvider', VeeValidate.ValidationProvider);
Vue.component('ValidationObserver', VeeValidate.ValidationObserver);
Vue.component('pane', Pane);
Vue.component('splitpanes', Splitpanes);
Vue.component('VueJsonPretty', VueJsonPretty);

// Export route components that are referenced by const name in the PHP inline script
window.VueExternalResources = ExternalResourcesComponent;
window.VueExternalResourcesEdit = ExternalResourcesEdit;
window.VueExternalResourcesCreate = ExternalResourcesCreate;
window.VueAdminMetadataEdit = AdminMetadataEdit;
window.VueMetadataTypes = MetadataTypes;
window.VueMetadataTypeEdit = MetadataTypeEdit;
window.VueDatafileEdit = DatafileEdit;
